### ISSUE TITLE
Roadmap to 1.0.0

### ISSUE THREAD

**Issue by n-shift** [shift-d/nv#2]
# README.md
## Installation
- [x] #1
## Comparison to other configs
- [x] Number of plugins
- [x] Why choose config
- [x] Installation
- [x] Amount of required things
## Screenshots
- [X] overview
- [X] dashboard
- [X] glow
- [X] nvimtree
- [X] completion
- [X] telescope
- [X] lualine
## Documentation
- [X] Settings
- [X] Plugins
- [X] (Auto)commands
- [X] Mappings
- [x] LSP

# Community
- [x] CONTRIBUTING.md
- [x] Reddit post
- [x] Create tutorial for extending nv

# Code
- [x] refactor options.lua in favor of verbosity
- [x] cleanup plugins.lua

# Plugins
- [x] Add lspsaga.nvim
